import SectionTitle from './ui/SectionTitle';
import MaintenanceCard from './dashboard/MaintenanceCard';
import { maintenanceRecommendations } from '../data/mockData';
import { motion } from 'framer-motion';
import { Wrench, CheckCircle2 } from 'lucide-react';

export default function PredictiveMaintenance() {
  return (
    <section id="maintenance" className="relative py-24 px-4">
      <div className="max-w-7xl mx-auto">
        <SectionTitle
          accent="Predictive Maintenance"
          title="AI-Powered Recommendations"
          subtitle="Actionable maintenance recommendations generated by AI analysis of sensor data, equipment history, and failure prediction models."
        />

        {/* Summary cards */}
        <motion.div
          className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-10 max-w-3xl mx-auto"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          {[
            { label: 'Active Recommendations', value: '3', color: 'text-blue-400' },
            { label: 'Critical Actions', value: '1', color: 'text-red-400' },
            { label: 'Est. Cost Savings', value: '$18,400', color: 'text-emerald-400' },
          ].map((item, i) => (
            <div key={i} className="glass-light p-4 rounded-xl text-center">
              <p className={`text-2xl font-bold font-mono ${item.color}`}>{item.value}</p>
              <p className="text-xs text-gray-500 mt-1">{item.label}</p>
            </div>
          ))}
        </motion.div>

        {/* Recommendation cards */}
        <div className="grid grid-cols-1 lg:grid-cols-1 gap-5 max-w-4xl mx-auto">
          {maintenanceRecommendations.map((rec, i) => (
            <MaintenanceCard key={rec.id} recommendation={rec} index={i} />
          ))}
        </div>

        {/* Maintenance impact */}
        <motion.div
          className="mt-12 glass p-6 rounded-2xl max-w-3xl mx-auto"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <div className="flex items-center gap-2 mb-4">
            <Wrench className="w-4 h-4 text-blue-400" />
            <span className="text-sm font-semibold text-gray-300">Predictive Maintenance Benefits</span>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {[
              'Reduces unplanned downtime by 67%',
              'Extends equipment lifetime by 25%',
              'Lowers maintenance costs by 42%',
              'Eliminates catastrophic failures',
              'Optimizes spare parts inventory',
              'Improves maintenance scheduling',
            ].map((benefit, i) => (
              <div key={i} className="flex items-center gap-2 text-sm text-gray-400">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0" />
                <span>{benefit}</span>
              </div>
            ))}
          </div>
        </motion.div>
      </div>
    </section>
  );
}
